spring:
  mongodb:
    uri: ${DIAGNOSTICS_MONGODB_URI}
    database: healthcare_diagnostics
    representation:
      uuid: standard
  data:
    mongodb:
      auto-index-creation: true
  mvc:
    problemdetails:
      enabled: true

server:
  shutdown: graceful

spring.lifecycle.timeout-per-shutdown-phase: 20s
